[tool.poetry]
name = "ujimaru-text-generate"
version = "0.0.1"
description = ""
authors = ["hppRC <hpp.ricecake@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/hppRC/ujimaru"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
